name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]  # Change this to your default branch if it's not 'main'
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: |
          # Create a temporary directory for the build
          mkdir -p .next-temp
          
          # Build the application
          npm run build
          
          # Remove API routes from the build output
          rm -rf out/_next/static/chunks/pages/api
          
          # Create necessary files for GitHub Pages
          touch out/.nojekyll
          echo "taxi-06565.pages.dev" > out/CNAME
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out
          branch: gh-pages
          clean: true